// Import framework
import Head from 'next/head'

// Import component
import Sidebar from '../components/sidebar'
import Content from '../components/layout/content'
import Header from '../components/layout/header'



// Import data
import { dataSidebar } from '../api/data-sidebar'

export default function Home() {
  return (
    <div className='my-blog'>
      <Head>
        <title>My Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header dataHeader = {dataSidebar} />
      <main className='main'>
        <Sidebar dataSidebar = {dataSidebar} />
        <Content />
       </main>
    </div>
  )
}
